name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # --- Install deps ---
      - name: Install Server deps
        working-directory: Server
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Install Website deps
        working-directory: Website
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      # --- Start API in background (only if you need it for build/tests) ---
      - name: Start API (background)
        working-directory: Server
        run: |
          node index.js &                        # start and return immediately
          echo $! > ../api.pid                  # save PID at repo root
          sleep 2                               # brief wait; replace with wait-on if needed

      # --- Build (don't use npm start here; it usually blocks) ---
      - name: Build website
        working-directory: Website
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            # fallback: replace with your real build command
            echo "No build script found. Add \"build\" to Website/package.json." && exit 1
          fi

      # --- Stop API even if build fails ---
      - name: Stop API
        if: always()
        run: |
          if [ -f api.pid ]; then
            kill "$(cat api.pid)" || true
            rm -f api.pid
          fi
