name: CI & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Pages needs these permissions
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_DIR: Website/build   # or Website/dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (cache for both subprojects)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            Server/package-lock.json
            Website/package-lock.json

      - name: Install Server deps
        working-directory: Server
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Install Website deps
        working-directory: Website
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Start API (background)  # remove if your build doesn't need the API
        working-directory: Server
        run: |
          node index.js &
          echo $! > ../api.pid
          sleep 2

      - name: Build website
        working-directory: Website
        run: |
          npm run build

      - name: Stop API
        if: always()
        run: |
          if [ -f api.pid ]; then kill "$(cat api.pid)" || true; rm -f api.pid; fi

      # Package the built static site for Pages
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # "lazy" answer for 404 page issue
      - name: Create 404.html SPA fallback
        working-directory: Website/build   # or Website/dist
        run: cp index.html 404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
